package Unity

import "strings"
import "github.com/imwithye/gitignore/template"

func init() {
	ignore := []string{
		"/Library/",
		"/[Tt]emp/",
		"/[Oo]bj/",
		"/[Bb]uild/",
		"/[Bb]uilds/",
		"/Assets/AssetStoreTools*",
		"",
		"# Autogenerated VS/MD solution and project files",
		"ExportedObj/",
		"*.csproj",
		"*.unityproj",
		"*.sln",
		"*.suo",
		"*.tmp",
		"*.user",
		"*.userprefs",
		"*.pidb",
		"*.booproj",
		"*.svd",
		"",
		"",
		"# Unity3D generated meta files",
		"*.pidb.meta",
		"",
		"# Unity3D Generated File On Crash Reports",
		"sysinfo.txt",
		"",
		"# Builds",
		"*.apk",
		"*.unitypackage",
	}
	template.SetTemplate("GitHub/Unity", strings.Join(ignore, "\n"))
}
