package Lazarus

import "strings"
import "github.com/imwithye/git_ignore/template"

func init() {
	ignore := []string{
		"# Lazarus compiler-generated binaries (safe to delete)",
		"*.exe",
		"*.dll",
		"*.so",
		"*.dylib",
		"*.lrs",
		"*.res",
		"*.compiled",
		"*.dbg",
		"*.ppu",
		"*.o",
		"*.or",
		"*.a",
		"",
		"# Lazarus autogenerated files (duplicated info)",
		"*.rst",
		"*.rsj",
		"*.lrt",
		"",
		"# Lazarus local files (user-specific info)",
		"*.lps",
		"",
		"# Lazarus backups and unit output folders.",
		"# These can be changed by user in Lazarus/project options.",
		"backup/",
		"*.bak",
		"lib/",
		"",
		"# Application bundle for Mac OS",
		"*.app/",
	}
	template.SetTemplate("GitHub/Global/Lazarus", strings.Join(ignore, "\n"))
}
