package Rust

import "strings"
import "github.com/imwithye/git_ignore/template"

func init() {
	ignore := []string{
		"# Generated by Cargo",
		"# will have compiled files and executables",
		"/target/",
		"",
		"# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries",
		"# More information here http://doc.crates.io/guide.html#cargotoml-vs-cargolock",
		"Cargo.lock",
	}
	template.SetTemplate("GitHub/Rust", strings.Join(ignore, "\n"))
}
